"""initial

Revision ID: 46434c4c201a
Revises: 
Create Date: 2025-03-09 20:23:13.378400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46434c4c201a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_migration_logs')
    op.add_column('iah_craft_my_songs', sa.Column('generated_timestamp', sa.Integer(), nullable=True))
    op.add_column('iah_craft_my_songs', sa.Column('upload_v1_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('iah_craft_my_songs', sa.Column('upload_v2_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('iah_craft_my_songs', sa.Column('song_duration_in_seconds', sa.Integer(), nullable=True))
    op.alter_column('playlists', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playlists', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('iah_craft_my_songs', 'song_duration_in_seconds')
    op.drop_column('iah_craft_my_songs', 'upload_v2_url')
    op.drop_column('iah_craft_my_songs', 'upload_v1_url')
    op.drop_column('iah_craft_my_songs', 'generated_timestamp')
    op.create_table('subscription_migration_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_package_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('new_package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_subscription_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('migration_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='subscription_migration_logs_pkey')
    )
    # ### end Alembic commands ###
